### ISSUE TITLE
Low framerate with big map

### ISSUE THREAD

**Issue by heubergen** [mozilla/lightbeam-we#217] opened 2017-10-03 22:17 UTC
Old issue: https://github.com/mozilla/lightbeam/issues/673

Here my map:
<img width="1021" alt="screen shot 2017-10-03 at 5 16 28 pm" src="https://user-images.githubusercontent.com/5529410/31151762-a092290e-a85e-11e7-8a86-4c7ca9960cf4.png">

The frame rate is still very low and doesn't allow me to use the map smoothly and efficient.

My hardware:
Macbook 12 Intel m3 CPU

**Comment by jonathanKingston** [comment] 2017-10-03 22:57
Hey,

Ao I think this is actually a duplicate of #212. Given that it only takes one erroneous response to make this happen and really slow down the graph when dragging I think we should focus on that and see if this fixes the issue.

Thanks!

**Comment by jonathanKingston** [comment] 2017-10-04 12:48
This was fixed for me with a similar size graph, granted I have a high end machine but if you could reopen after testing 2.0.3 that would be great.
Thanks

**Closed by jonathanKingston** 2017-10-04 12:48 UTC

**Comment by heubergen** [comment] 2017-10-04 19:52
I can see some improvements (e.g. the animations start now) but still the frame rate is very low when I start to navigate through the galaxy.
