### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by nukeador** [mozilla/lightbeam-we#245] opened 2018-05-07 18:27 UTC
Hi,

I've found out this extension is not l10n friendly and can't be localized. It would be great to be l10n ready so we can localize in many other languages to extend its reach ;-)

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

Context: I'm running a research on addons and localization to inform a campaign at Mozilla Open Innovation team and Lightbeam was one of the extensions in our radar ;-)

**Comment by cadeyrn** [comment] 2018-05-07 18:38
duplicate of #215

**Closed** 2018-05-08 05:07 UTC
