### ISSUE TITLE
UI elements missing from WebExtension

### ISSUE THREAD

**Issue by cbyrd01** [mozilla/lightbeam-we#237] opened 2017-12-09 22:09 UTC
The Visualization section in the upper left corner currently shows "Graph" button, does not show "Clock" or "List". "Toggle Controls" section missing at bottom, and right hand panels are also missing.

This appears to be a regression from the legacy SDK add-on. 

This was tested using Lightbeam 2.0.4 and lightbeam-we/master on Firefox build 57.0.2 (20171206182557) on Windows 10 64-bit. 

Thank you for developing this very useful extension!

**Comment by princiya** [comment] 2017-12-10 02:52
Hi @cbyrd01,

Thank you for using Lightbeam.

This issue is a duplicate of this #236. Please check this [comment](https://github.com/mozilla/lightbeam-we/issues/236#issuecomment-348740370) for more explanation.

**Closed by princiya** 2017-12-10 02:52 UTC

**Comment by xlxsobvrzo** [comment] 2017-12-10 04:08
Mil gracias, hermano, blessed be,  Linux change my sad life... thanks for
your beutiful brain

2017-12-09 14:09 GMT-08:00 Christopher Byrd <notifications@github.com>:
